name: exampleの出力結果画像が最新かどうかのテスト

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

defaults:
  run:
    shell: bash --noprofile --norc -euxo pipefail {0}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v2

      - name: sassコマンドのインストール
        run: npm install -g sass

      - name: コミットに含まれるスライド画像をバックアップ
        run: mkdir example-backup && mv example/example.0* example-backup

      - name: 一度すべて削除して再ビルド
        run: make clean all

      - name: 再ビルドの結果がコミットした結果と一致しているかチェック
        run: |
          result="$(composite -compose difference \
            example/example.001.png \
            example-backup/example.001.png \
            - | \
            identify -format "%[mean]" -)"
          (( $(echo "0.001 > $result" |bc -l) ))

          result="$(composite -compose difference \
            example/example.002.png \
            example-backup/example.002.png \
            - | \
            identify -format "%[mean]" -)"
          (( $(echo "0.001 > $result" |bc -l) ))

      - name: 検証しやすいようにビルド結果をartifactへ保存
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: example
          path: example
          if-no-files-found: error

      - name: 結果画像をコミットへ貼り付け
        uses: actions/github-script@v4
        with:
          script: |
            const script = require('./.github/github-script.js')
            await script({github, context, core})
