name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build slide images
        run: npx @marp-team/marp-cli@latest example.md --images png
        working-directory: example

      - uses: actions/github-script@v4
        with:
          script: |
            const script = require('./.github/github-script.js')
            await script({github, context, core})
