name: exampleの出力結果画像が最新かどうかのテスト

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install sass command
        run: npm install -g sass

      - name: Build slide images
        run: |
          set -eux
          make clean all
          test "$(git status -s | wc -l)" -eq 0

      - uses: actions/upload-artifact@v2
        with:
          name: example
          path: example
          if-no-files-found: error
