name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build slide images
        run: |
          set dir_name=latest-images
          mkdir $dir_name
          npx @marp-team/marp-cli@latest example.md --images png --output $dir_name
        working-directory: example
