name: exampleの出力結果画像が最新かどうかのテスト

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v2

      - name: sassコマンドのインストール
        run: npm install -g sass

      - name: 一度すべて削除して再ビルド
        run: make clean all

      - name: 再ビルドの結果がコミットした結果と一致しているかチェック
        run: test "$(git status -s | wc -l)" -eq 0

      - name: 検証しやすいようにビルド結果をartifactへ保存
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: example
          path: example
          if-no-files-found: error
